import { Inter } from 'next/font/google'
import Cabecalho from '@/components/Cabecalho/Cabecalho';
import "./globals.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'FiapTech',
  description: 'Generated by FiapTech',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Cabecalho/>
        {children}
      </body>
    </html>
  )
}
